### ISSUE TITLE
Um crash bc of a minecraft horse?

### ISSUE THREAD

**Issue by FullMetalMaster** [team-abnormals/abnormals-core#65]
minecraft:skeleton_horse (net.minecraft.entity.passive.horse.SkeletonHorseEntity)

Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

no idea

**Comment by bageldotjpg** [comment]
post the full log

**Comment by FullMetalMaster** [comment]
https://www.mediafire.com/file/040ye9jxb37at1c/server70031_-_7_Jan_2021_20_37_52.zip/file all the logs

**Comment by SmellyModder** [comment]
Don't send all your logs. Only send the logs containing that stack trace you sent.
I also assume you opened this issue because you noticed the `mixin:APP:abnormals_core.mixins.json:ServerWorldMixin` part in the stack trace. Our `ServerWorldMixin` doesn't affect anything to do with entity ticking, so I don't think this is an issue caused by this mod.
